### ISSUE TITLE
How to use the scipy library for Buttterworth filters

### ISSUE THREAD

**Issue by ayyyyyyyyyyLMAO** [waltergallegog/classificationsTaskSCNN#1]
Since for the SoC project the scipy library is used and from it the function [butter](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.butter.html) for generating the filter I wouls like to ask about one thing that is a bit unclear. 

When 'bandpass' or 'bandstop' is used the overall order of the biquad cascade is going to be double the order passed to the function. If we set order (N) to 2 we get two instances of second order cascades, which means the resulting order of 4. 

For the SoC project we are using a low-power MCU and we want to make things as simpler as possible because we want to get the best performance possible.

With this being said, is this the lowest overall order that we can get for this filter configuration or is it possible to somehow get the resulting second order cascades of lower overall order?

**Comment by ayyyyyyyyyyLMAO** [comment]
@waltergallegog I couldn't assign this to you so I use this @ feature just in case so that you see on time.

**Comment by waltergallegog** [comment]
I have checked with Riccardo and the use of N=2 (order 4) was on purpose.

We suggest to use order 4 also for the implementation with the SensorTile, as we know that with filters of this order we can obtain good results.

However if during the implementation and testing you discover that the SensorTile is not able to manage filters of order 4 with acceptable latency, you can try with order 2. This will decrease the accuracy of the encoding but we may not have other option. The order (as well as the number of filters in the bank) becomes a parameter that we can tune to obtain an acceptable trade-off between speed and accuracy.

**Comment by ayyyyyyyyyyLMAO** [comment]
Understood, we will try it out and see and update here again if needed. Thanks!
